### ISSUE TITLE
func DomainGetInfo("mydomain.com") don't work?

### ISSUE THREAD

**Issue by remotejob** [billputer/go-namecheap#22]
`2018/09/05 05:24:53 strconv.ParseBool: parsing "NotAlloted": invalid syntax
panic: strconv.ParseBool: parsing "NotAlloted": invalid syntax`

**Comment by mrThe** [comment]
Error raised in case of whois guard is not allowed. Namecheap devs made a typo on "NotAllowed".
Hotfix: in `domain.go`, find struct  `Whoisguard` and change option `Enabled` from `bool` to `string`.

It will compile and work, but I'm don't sure if this change does not break anything.

**Comment by fastest963** [comment]
It's not a typo. It means that you didn't purchase Whoisguard for that domain. You might not be able to purchase it for some domains, but I've seen `NotAlloted` for domains where it is available but just not purchased yet.

Anyways, this is fixed in my PR.
